language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.5"
before_install:
  - pip install nose coverage
script:
  - nosetests -v --with-coverage --cover-inclusive --cover-package=kqml
